### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by mholtrlc** [concerto-addons/concerto_template_scheduling#13]
I am receiving a 500 error when trying to use this plugin

````

I, [2015-03-09T14:55:51.919250 #25727]  INFO -- : Started GET "/screens/1" for 10.20.20.140 at 2015-03-09 14:55:51 -0400
I, [2015-03-09T14:55:51.921317 #25727]  INFO -- : Processing by ScreensController#show as HTML
I, [2015-03-09T14:55:51.921385 #25727]  INFO -- :   Parameters: {"id"=>"1"}
I, [2015-03-09T14:55:51.949962 #25727]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/concerto_hardware-0.2/app/views/concerto_hardware/screens/_screen_link.html.erb (0.4ms)
W, [2015-03-09T14:55:51.951242 #25727]  WARN -- : ConcertoPlugin: use_plugin_ability: No Ability found for ConcertoTemplateScheduling
I, [2015-03-09T14:55:51.962151 #25727]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/concerto_template_scheduling-0.0.5/app/views/concerto_template_scheduling/screens/_screen_link.html.erb (10.7ms)
I, [2015-03-09T14:55:51.962294 #25727]  INFO -- :   Rendered screens/show.html.erb within layouts/application (20.8ms)
I, [2015-03-09T14:55:51.962511 #25727]  INFO -- : Completed 500 Internal Server Error in 41ms
E, [2015-03-09T14:55:52.254225 #25727] ERROR -- : ** [Airbrake] Failure: Net::HTTPBadGateway
F, [2015-03-09T14:55:52.257374 #25727] FATAL -- : 
ActionView::Template::Error (757: unexpected token at 'custom'):
    34:                   <p>
    35:                     <%= link_to(template_scheduling.schedule_path(schedule)) do %>
    36:                       <%= l(schedule.start_time.to_date, :format => :short) %> - <%= l(schedule.end_time.to_date, :format => :short) %>
    37:                     <% end %> <b><%= schedule.is_effective? ? t(:active) : '' %></b>
    38:                   </p>
    39:                   <p><b><%= ConcertoTemplateScheduling::Schedule::DISPLAY_WHEN.key(schedule.config['display_when'].to_i) %></b></p>
    40: 
  app/models/concerto_plugin.rb:110:in `block (2 levels) in render_view_hook'
  app/models/concerto_plugin.rb:106:in `each'
  app/models/concerto_plugin.rb:106:in `block in render_view_hook'
  app/models/concerto_plugin.rb:104:in `render_view_hook'
  app/views/screens/show.html.erb:1:in `_app_views_screens_show_html_erb__1238938330362039728_50515320'
  app/controllers/screens_controller.rb:24:in `show'
  app/controllers/application_controller.rb:112:in `set_time_zone'


I, [2015-03-09T14:55:52.257953 #25727]  INFO -- : Processing by ErrorsController#render_error as HTML
I, [2015-03-09T14:55:52.258016 #25727]  INFO -- :   Parameters: {"id"=>"1"}
I, [2015-03-09T14:55:52.261507 #25727]  INFO -- :   Rendered errors/error_generic.html.erb within layouts/no-topmenu (0.6ms)
I, [2015-03-09T14:55:52.262363 #25727]  INFO -- :   Rendered elements/_head.html.erb (0.1ms)
I, [2015-03-09T14:55:52.262772 #25727]  INFO -- : Completed 500 Internal Server Error in 5ms (Views: 2.2ms | ActiveRecord: 0.3ms)
````

**Comment by augustf** [comment]
I've pushed a new gem with the corresponding change from content-scheduling and released it as 0.0.6.

**Comment by mholtrlc** [comment]
That fixed most of the issues (can create and edit schedules now) but still getting a 500 when I go to the "All Schedules" page.

````

I, [2015-03-09T16:59:18.852003 #32706]  INFO -- : Started GET "/template-scheduling/schedules" for 10.20.20.140 at 2015-03-09 16:59:18 -0400
I, [2015-03-09T16:59:18.853658 #32706]  INFO -- : Processing by ConcertoTemplateScheduling::SchedulesController#index as HTML
I, [2015-03-09T16:59:18.887523 #32706]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/concerto_template_scheduling-0.0.5/app/views/concerto_template_scheduling/schedules/index.html.erb within layouts/application (5.2ms)
I, [2015-03-09T16:59:18.887724 #32706]  INFO -- : Completed 500 Internal Server Error in 34ms
E, [2015-03-09T16:59:19.166552 #32706] ERROR -- : ** [Airbrake] Failure: Net::HTTPBadGateway
F, [2015-03-09T16:59:19.169953 #32706] FATAL -- : 
ActionView::Template::Error (757: unexpected token at 'custom'):
    36:             <td>
    37:               <%= ConcertoTemplateScheduling::Schedule.human_attribute_name(:start_time)%>: <%= l(schedule.start_time, :format => :long) %><br/>
    38:               <%= ConcertoTemplateScheduling::Schedule.human_attribute_name(:end_time)%>: <%= l(schedule.end_time, :format => :long) %><br/>
    39:               <%= t('concerto_template_scheduling.effective') %>: <b><%= schedule.is_effective? ? t(:yes) : t(:no) %></b>
    40:             </td>
    41:             <td>
    42:               <b><%= ConcertoTemplateScheduling::Schedule::DISPLAY_WHEN.key(schedule.config['display_when'].to_i) %></b><br/>
  app/controllers/application_controller.rb:112:in `set_time_zone'


I, [2015-03-09T16:59:19.170520 #32706]  INFO -- : Processing by ErrorsController#render_error as HTML
I, [2015-03-09T16:59:19.175878 #32706]  INFO -- :   Rendered errors/error_generic.html.erb within layouts/no-topmenu (0.7ms)
I, [2015-03-09T16:59:19.176848 #32706]  INFO -- :   Rendered elements/_head.html.erb (0.1ms)
I, [2015-03-09T16:59:19.177336 #32706]  INFO -- : Completed 500 Internal Server Error in 7ms (Views: 2.5ms | ActiveRecord: 0.7ms)
I, [2015-03-09T16:59:19.528143 #32706]  INFO -- : Started GET "/assets/layout/pagebg.gif" for 10.20.20.140 at 2015-03-09 16:59:19 -0400
F, [2015-03-09T16:59:19.529409 #32706] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/assets/layout/pagebg.gif"):
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:16:in `_call'
  vendor/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:12:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:514:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/application.rb:144:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/railtie.rb:194:in `public_send'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.7/lib/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'


I, [2015-03-09T16:59:19.529963 #32706]  INFO -- : Processing by ErrorsController#render_error as HTML
I, [2015-03-09T16:59:19.540970 #32706]  INFO -- :   Rendered errors/error_404.html.erb within layouts/application (0.6ms)
I, [2015-03-09T16:59:19.543593 #32706]  INFO -- :   Rendered elements/_head.html.erb (0.1ms)
I, [2015-03-09T16:59:19.556177 #32706]  INFO -- :   Rendered elements/_topmenu_contents.html.erb (12.3ms)
I, [2015-03-09T16:59:19.556467 #32706]  INFO -- :   Rendered elements/_render_flash.html.erb (0.1ms)
I, [2015-03-09T16:59:19.560913 #32706]  INFO -- :   Rendered layouts/_footer.html.erb (4.2ms)
I, [2015-03-09T16:59:19.561759 #32706]  INFO -- :   Rendered layouts/_analytics.html.erb (0.6ms)
I, [2015-03-09T16:59:19.562032 #32706]  INFO -- : Completed 404 Not Found in 32ms (Views: 20.1ms | ActiveRecord: 2.8ms)
root@concerto:/usr/share/concerto/log# 
````

**Comment by mfrederickson** [comment]
@augustf [this](https://github.com/concerto/concerto/blob/master/app/views/activity_mailer/submission_update.html.erb#L16) is the only reference to pagebg.gif that I could find and it seems to point to a file that does not exist under our assets folder.  If I'm reading things right, maybe @zr2d2 just missed putting that file out there in 4797e1043902f96fe25abe9476d5742519f546b3.  I don't know if it will solve @mholtrlc's problem, but it does seem to be one of them in the error output above.

**Comment by augustf** [comment]
Well it seems in 4797e1043902f96fe25abe9476d5742519f546b3 that @zr2d2 just refactored it. In the diff, I can see that reference to page_bg still.

**Comment by mfrederickson** [comment]
You're right, I didn't see it was off screen.  Sorry.  I think it was in 8c5e77d26a5d579ae59ead9e12852a2d37949b0b

**Comment by augustf** [comment]
@kench Any idea what page_bg.gif was supposed to be?

**Comment by augustf** [comment]
I couldn't track down that what was supposed to be, so in the course of making email work in https://github.com/concerto/concerto/commit/215a487a901625089d7d4ebc847b1a9392c19b71 , I just removed it.
